substitutions:
  name: "kids-room-bedlight"
  num_leds: '66'
  max_led_idx: '65'
  gamma_correct: '1.5'

esphome:
  name: ${name}
  project:
    name: "hexalight.lowpoly-butterfly"
    version: "1.0.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lowpoly-Butterfly"
    password: !secret ap_password

captive_portal:

# web_server:
#   port: 80

switch:
  - platform: restart
    name: "Restart Light"

# esp32_improv:
#   authorizer: none

light:
  - platform: partition
    name: ${name}
    id: lowpoly
    restore_mode: ALWAYS_OFF
    gamma_correct: ${gamma_correct}
    segments:
      - id: right_wing
        from: 0
        to: ${max_led_idx}
      - id: left_wing
        from: 0
        to: ${max_led_idx}
    effects:
      - addressable_lambda:
          name: "Reading Light"
          update_interval: 1s
          lambda: |-
            it.all()= Color(255, 170, 160);
            return;
      - addressable_rainbow:
          name: "Rainbow"
          width: ${num_leds}
      - addressable_twinkle:
          name: "Twinkle"
      - addressable_lambda:
          name: "Voronoi"
          update_interval: 1ms
          lambda: |-
            // Time, in miliseconds, needed for each segment to transition to new random color
            static const uint16_t segtrans = 200;

            // Number of segments
            static const uint8_t nsegments = 18;

            // End indices for each segment
            static const uint8_t ranges[nsegments] = {7, 14, 20, 33, 36, 50, 54, 59, 65, \
                                                      72, 79, 85, 98, 101, 115, 119, 124, 131};

            // Number of steps in each transition
            static const uint16_t steps = segtrans / 1;

            static uint16_t progress = 1;

            // Base, starting color
            static uint8_t start_colors[nsegments] = {127};
            static uint8_t target_colors[nsegments] = {0};

            static float segcolors[nsegments] = {0};

            if (initial_run || progress == steps) {
              // Generate random new target color for each segment
              random_bytes(target_colors, nsegments);
              // Clip values
              for (uint8_t ii = 0; ii < nsegments; ii++) {
                target_colors[ii] = min(target_colors[ii], (uint8_t)164);
              }
              progress = 1;
            }

            uint8_t start = 0;
            uint8_t end = 0;

            for(uint8_t ii = 0; ii < nsegments; ii++) {
              end = ranges[ii] + 1;
              float k = (float)(target_colors[ii] - start_colors[ii]) / (float)steps;
              segcolors[ii] = start_colors[ii] + k * progress;
              it.range(start, end) = Color(220, (uint8_t)segcolors[ii], 0);
              start = end;
            }
            progress++;

            if (progress == steps) {
              memcpy(start_colors, target_colors, nsegments);
            }

            return;

  - platform: fastled_clockless
    gamma_correct: ${gamma_correct}
    restore_mode: ALWAYS_OFF
    rgb_order: GRB
    chipset: WS2813
    pin: GPIO22
    num_leds: ${num_leds}
    name: "Right Wing"
    id: right_wing
    internal: true

  - platform: neopixelbus
    gamma_correct: ${gamma_correct}
    restore_mode: ALWAYS_OFF
    type: GRB
    variant: WS2813
    pin: GPIO23
    num_leds: ${num_leds}
    name: "Left Wing"
    id: left_wing
    internal: true

esp32_touch:
  setup_mode: false
  iir_filter: 15ms
  low_voltage_reference: 0.5V
  high_voltage_reference: 2.7V
  voltage_attenuation: 1.5V

binary_sensor:
  - platform: esp32_touch
    name: "On/Off"
    pin: GPIO32
    threshold: 1150
    filters:
      - delayed_on_off: 50ms
    on_click:
      - min_length: 800ms
        max_length: 5000ms
        then:
          - light.turn_off: lowpoly
      - min_length: 50ms
        max_length: 700ms
        then:
          lambda: |-
            static const int levels = 5;
            static const float brightness_levels[levels] = {0.0, 0.15, 0.45, 0.8, 1.0};

            static int current_level = 0;

            current_level = (current_level + 1) % (levels);

            auto effects = id(lowpoly).get_effects();
            std::string effect_name = id(lowpoly).get_effect_name();
            if (effect_name == "None") {
              effect_name = effects.front()->get_name();
            }

            if (current_level > 0) {
              auto call = id(lowpoly).turn_on();
              float brightness = brightness_levels[current_level];
              call.set_brightness(brightness);
              call.set_effect(effect_name);
              call.perform();
            }
            else {
              auto call = id(lowpoly).turn_off();
              call.perform();
            }
            return;

  - platform: esp32_touch
    name: "Toggle Effect"
    pin: GPIO33
    threshold: 1050
    filters:
      - delayed_on_off: 100ms
    on_click:
    - min_length: 800ms
      max_length: 5000ms
      then:
        - light.turn_off: lowpoly
    - min_length: 50ms
      max_length: 700ms
      then:
        lambda: |-
            auto call = id(lowpoly).turn_on();

            auto effects = id(lowpoly).get_effects();
            std::string name = id(lowpoly).get_effect_name();

            uint8_t i = 0;

            if (name != "None") {
              // There's an effect in progress, move to the next one
              for (auto e : effects) {
                ++i %= effects.size();
                if (e->get_name() == name) {
                  break;
                }
              }
            }

            call.set_effect(effects[i]->get_name());
            call.perform();
            return;
